package views.frames;

import java.awt.Toolkit;
import javax.swing.JButton;
import views.helper.JTextFieldLimit;

/**
 *
 * @author skuarch
 */
public class Login extends javax.swing.JFrame {

    //==========================================================================
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(getRootPane());
        setIconImage(Toolkit.getDefaultToolkit().getImage(Login.class.getResource("/views/images/ssnIcon.png")));
    } // end Login    

    //==========================================================================
    public void setMessage(String message) {
        jLabelMessage.setText(message);
    } // end setMessage

    //==========================================================================
    public void setUser(String text) {
        jTextFieldUser.setText(text);
    } // end setUser

    //==========================================================================
    public void setPassword(String text) {
        jPasswordField.setText(text);
    } // end setPassword

    //==========================================================================
    public char[] getPassword() {
        return jPasswordField.getPassword();
    } // end getPassword

    //==========================================================================
    public String getUser() {
        return jTextFieldUser.getText();
    } // end getUser

    //==========================================================================
    public JButton getLoginButton() {
        return this.jButtonLogin;
    } // end getLoginButton

    //==========================================================================
    public JButton getCancelButton() {
        return this.jButtonCancel;
    } // end getCancelButton

    //==========================================================================
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jLabelMessage = new javax.swing.JLabel();
        jTextFieldUser = new javax.swing.JTextField(8);
        jButtonLogin = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jLabelClient = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField(8);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sispro Sniffer Network");
        setResizable(false);

        jLabelTitle.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(0, 148, 205));
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/headLogin.png"))); // NOI18N

        jLabelMessage.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabelMessage.setForeground(new java.awt.Color(153, 51, 0));
        jLabelMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMessage.setText(" ");

        jTextFieldUser.setDocument(new JTextFieldLimit(8));

        jButtonLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/login.png"))); // NOI18N
        jButtonLogin.setText("login");

        jButtonCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/cancel.png"))); // NOI18N
        jButtonCancel.setText("cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jLabelClient.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabelClient.setForeground(new java.awt.Color(0, 72, 106));
        jLabelClient.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelClient.setText("General DataComm de México");

        jPasswordField.setDocument(new JTextFieldLimit(8));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelClient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelTitle)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabelMessage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPasswordField)
                    .addComponent(jTextFieldUser, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonLogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancel)))
                .addGap(88, 88, 88))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelTitle)
                .addGap(12, 12, 12)
                .addComponent(jLabelMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLogin)
                    .addComponent(jButtonCancel))
                .addGap(18, 18, 18)
                .addComponent(jLabelClient)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //==========================================================================
    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JLabel jLabelClient;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextFieldUser;
    // End of variables declaration//GEN-END:variables
}
