package views.frames;

import java.awt.Toolkit;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import javax.swing.JTabbedPane;

/**
 *
 * @author skuarch
 */
public class MainFrame extends javax.swing.JFrame {

    //==========================================================================
    public MainFrame() {
        initComponents();
        setLocationRelativeTo(getRootPane());
        setIconImage(Toolkit.getDefaultToolkit().getImage(MainFrame.class.getResource("/views/images/ssnIcon.png")));
        setExtendedState(MAXIMIZED_BOTH);
    }

    public JMenu getjMenuAbout() {
        return jMenuAbout;
    }

    public JMenu getjMenuFile() {
        return jMenuFile;
    }

    public JMenuItem getjMenuItemEndToEnd() {
        return jMenuItemEndToEnd;
    }

    public JMenuItem getjMenuItemEventViewer() {
        return jMenuItemEventViewer;
    }

    public JMenuItem getjMenuItemExit() {
        return jMenuItemExit;
    }

    public JMenuItem getjMenuItemGenerateReport() {
        return jMenuItemGenerateReport;
    }

    public JMenuItem getjMenuItemNetworkScanner() {
        return jMenuItemNetworkScanner;
    }

    public JMenuItem getjMenuItemSearchIPAddress() {
        return jMenuItemSearchIPAddress;
    }

    public JMenuItem getjMenuItemSearchPort() {
        return jMenuItemSearchPort;
    }

    public JMenuItem getjMenuItemSearchSubnet() {
        return jMenuItemSearchSubnet;
    }

    public JMenu getjMenuModeler() {
        return jMenuShaper;
    }

    public JMenu getjMenuTools() {
        return jMenuTools;
    }

    public JMenuItem getjMenuItemAbout() {
        return jMenuItemAbout;
    }

    public JMenu getjMenuConfiguration() {
        return jMenuConfiguration;
    }

    public JMenuItem getjMenuItemConfiguration() {
        return jMenuItemConfiguration;
    }

    public JMenuItem getjMenuItemModelerChains() {
        return jMenuItemModelerChains;
    }

    public JMenu getjMenuModelerManage() {
        return jMenuModelerManage;
    }

    public JMenu getjMenuModelerMonitoring() {
        return jMenuModelerMonitoring;
    }

    public JMenu getjMenuModelerSettings() {
        return jMenuModelerSettings;
    }

    public JMenu getjMenuModelerTools() {
        return jMenuModelerTools;
    }

    public JMenu getjMenuRules() {
        return jMenuRules;
    }

    public JSplitPane getjSplitPaneMain() {
        return jSplitPaneMain;
    }

    public JSplitPane getjSplitPaneTrees() {
        return jSplitPaneTrees;
    }

    public JTabbedPane getjTabbedPaneCollectors() {
        return jTabbedPaneCollectors;
    }

    public JTabbedPane getjTabbedPaneTreeViews() {
        return jTabbedPaneTreeViews;
    }

    public JPanel getjPanelCenter() {
        return jPanelCenter;
    }    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPaneMain = new javax.swing.JSplitPane();
        jPanelCenter = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSplitPaneTrees = new javax.swing.JSplitPane();
        jTabbedPaneTreeViews = new javax.swing.JTabbedPane();
        jTabbedPaneCollectors = new javax.swing.JTabbedPane();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenuTools = new javax.swing.JMenu();
        jMenuItemEventViewer = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSearchIPAddress = new javax.swing.JMenuItem();
        jMenuItemSearchPort = new javax.swing.JMenuItem();
        jMenuItemSearchSubnet = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemNetworkScanner = new javax.swing.JMenuItem();
        jMenuItemEndToEnd = new javax.swing.JMenuItem();
        jMenuItemGenerateReport = new javax.swing.JMenuItem();
        jMenuConfiguration = new javax.swing.JMenu();
        jMenuItemConfiguration = new javax.swing.JMenuItem();
        jMenuShaper = new javax.swing.JMenu();
        jMenuModelerManage = new javax.swing.JMenu();
        jMenuItemModelerChains = new javax.swing.JMenuItem();
        jMenuModelerSettings = new javax.swing.JMenu();
        jMenuRules = new javax.swing.JMenu();
        jMenuModelerMonitoring = new javax.swing.JMenu();
        jMenuModelerTools = new javax.swing.JMenu();
        jMenuAbout = new javax.swing.JMenu();
        jMenuItemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPaneMain.setDividerLocation(200);

        jPanelCenter.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/watermark.png"))); // NOI18N

        javax.swing.GroupLayout jPanelCenterLayout = new javax.swing.GroupLayout(jPanelCenter);
        jPanelCenter.setLayout(jPanelCenterLayout);
        jPanelCenterLayout.setHorizontalGroup(
            jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
            .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelCenterLayout.createSequentialGroup()
                    .addGap(0, 87, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 88, Short.MAX_VALUE)))
        );
        jPanelCenterLayout.setVerticalGroup(
            jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
            .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelCenterLayout.createSequentialGroup()
                    .addGap(0, 177, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 177, Short.MAX_VALUE)))
        );

        jSplitPaneMain.setRightComponent(jPanelCenter);

        jSplitPaneTrees.setDividerLocation(240);
        jSplitPaneTrees.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPaneTrees.setTopComponent(jTabbedPaneTreeViews);
        jSplitPaneTrees.setRightComponent(jTabbedPaneCollectors);

        jSplitPaneMain.setLeftComponent(jSplitPaneTrees);

        jMenuFile.setText("File");

        jMenuItemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/shutdown-mini.png"))); // NOI18N
        jMenuItemExit.setText("exit");
        jMenuFile.add(jMenuItemExit);

        jMenuBar.add(jMenuFile);

        jMenuTools.setText("Tools");

        jMenuItemEventViewer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/eventViewer.png"))); // NOI18N
        jMenuItemEventViewer.setText("event viewer");
        jMenuTools.add(jMenuItemEventViewer);
        jMenuTools.add(jSeparator1);

        jMenuItemSearchIPAddress.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/ip.png"))); // NOI18N
        jMenuItemSearchIPAddress.setText("search ip address");
        jMenuTools.add(jMenuItemSearchIPAddress);

        jMenuItemSearchPort.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/connect.png"))); // NOI18N
        jMenuItemSearchPort.setText("search port");
        jMenuTools.add(jMenuItemSearchPort);

        jMenuItemSearchSubnet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/subnet.png"))); // NOI18N
        jMenuItemSearchSubnet.setText("search subnet");
        jMenuTools.add(jMenuItemSearchSubnet);
        jMenuTools.add(jSeparator2);

        jMenuItemNetworkScanner.setText("network scanner");
        jMenuTools.add(jMenuItemNetworkScanner);

        jMenuItemEndToEnd.setText("end to end");
        jMenuTools.add(jMenuItemEndToEnd);

        jMenuItemGenerateReport.setText("generate report");
        jMenuTools.add(jMenuItemGenerateReport);

        jMenuBar.add(jMenuTools);

        jMenuConfiguration.setText("Configuration");

        jMenuItemConfiguration.setText("configuration");
        jMenuConfiguration.add(jMenuItemConfiguration);

        jMenuBar.add(jMenuConfiguration);

        jMenuShaper.setText("Shaper");

        jMenuModelerManage.setText("manage");

        jMenuItemModelerChains.setText("chains");
        jMenuModelerManage.add(jMenuItemModelerChains);

        jMenuShaper.add(jMenuModelerManage);

        jMenuModelerSettings.setText("settings");
        jMenuShaper.add(jMenuModelerSettings);

        jMenuRules.setText("rules");
        jMenuShaper.add(jMenuRules);

        jMenuModelerMonitoring.setText("monitoring");
        jMenuShaper.add(jMenuModelerMonitoring);

        jMenuModelerTools.setText("tools");
        jMenuShaper.add(jMenuModelerTools);

        jMenuBar.add(jMenuShaper);

        jMenuAbout.setText("Help");

        jMenuItemAbout.setText("about");
        jMenuAbout.add(jMenuItemAbout);

        jMenuBar.add(jMenuAbout);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPaneMain, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPaneMain)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenuAbout;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuConfiguration;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItemAbout;
    private javax.swing.JMenuItem jMenuItemConfiguration;
    private javax.swing.JMenuItem jMenuItemEndToEnd;
    private javax.swing.JMenuItem jMenuItemEventViewer;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemGenerateReport;
    private javax.swing.JMenuItem jMenuItemModelerChains;
    private javax.swing.JMenuItem jMenuItemNetworkScanner;
    private javax.swing.JMenuItem jMenuItemSearchIPAddress;
    private javax.swing.JMenuItem jMenuItemSearchPort;
    private javax.swing.JMenuItem jMenuItemSearchSubnet;
    private javax.swing.JMenu jMenuModelerManage;
    private javax.swing.JMenu jMenuModelerMonitoring;
    private javax.swing.JMenu jMenuModelerSettings;
    private javax.swing.JMenu jMenuModelerTools;
    private javax.swing.JMenu jMenuRules;
    private javax.swing.JMenu jMenuShaper;
    private javax.swing.JMenu jMenuTools;
    private javax.swing.JPanel jPanelCenter;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JSplitPane jSplitPaneMain;
    private javax.swing.JSplitPane jSplitPaneTrees;
    private javax.swing.JTabbedPane jTabbedPaneCollectors;
    private javax.swing.JTabbedPane jTabbedPaneTreeViews;
    // End of variables declaration//GEN-END:variables
}
